// Generated by `pnpm --filter @cz-epf/api db:types` from the migrated
// database. Do not edit: change a migration and regenerate.

/** A row of `forecast`. */
export interface ForecastRow {
  delivery_date: string;
  period_ordinal: number;
  resolution_minutes: number;
  model: string;
  run_type: string;
  price: string;
  model_version: string;
  code_version: string;
  executed_at: Date;
}

/** A row of `model_comparison`. */
export interface ModelComparisonRow {
  model_a: string;
  model_b: string;
  run_type: string;
  period_ordinal: number;
  resolution_minutes: number;
  dm_statistic: string;
  p_value: string;
  computed_at: Date;
}

/** A row of `observed_price`. */
export interface ObservedPriceRow {
  delivery_start: Date;
  resolution_minutes: number;
  price: string;
  source: string;
  retrieved_at: Date;
}

/** A row of `published_metric`. */
export interface PublishedMetricRow {
  model: string;
  run_type: string;
  scope_type: string;
  scope_start: string;
  metric: string;
  value: string;
  n_forecasts: number;
  computed_at: Date;
}

/** A row of `repaired_observed_price`. */
export interface RepairedObservedPriceRow {
  delivery_date: string;
  period_ordinal: number;
  resolution_minutes: number;
  price: string;
}
