/**
 * Generates `src/db.generated.ts` from the live database (ADR-0004): the
 * migrations are the source of truth, and TypeScript reads the schema they
 * produce rather than restating it.
 *
 *     pnpm --filter @cz-epf/api db:types
 *
 * reads `DATABASE_URL`, defaulting to the local compose Postgres. The output is
 * committed and the pull request gate regenerates it and fails on a
 * difference, as it does for `db/schema.sql`.
 */
import { writeFileSync } from "node:fs";
import postgres from "postgres";

import { LOCAL_DATABASE_URL, PG_TYPES } from "../src/db.ts";

// What `src/db.ts`'s client hands back for each column type.
const TS_TYPES: Record<string, string> = {
  date: "string",
  integer: "number",
  numeric: "string",
  text: "string",
  "timestamp with time zone": "Date",
};

const url = process.env["DATABASE_URL"] ?? LOCAL_DATABASE_URL;
const sql = postgres(url, { types: PG_TYPES });

const columns = await sql<
  {
    table_name: string;
    column_name: string;
    data_type: string;
    is_nullable: string;
  }[]
>`
  SELECT table_name, column_name, data_type, is_nullable
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name <> 'schema_migrations'
  ORDER BY table_name, ordinal_position
`;
await sql.end();

const tables = new Map<string, string[]>();
for (const c of columns) {
  const type = TS_TYPES[c.data_type];
  if (type === undefined) {
    throw new Error(
      `no TypeScript type for ${c.table_name}.${c.column_name}: ${c.data_type}`,
    );
  }
  const nullable = c.is_nullable === "YES" ? " | null" : "";
  const lines = tables.get(c.table_name) ?? [];
  lines.push(`  ${c.column_name}: ${type}${nullable};`);
  tables.set(c.table_name, lines);
}

const pascal = (name: string): string =>
  name.replace(/(^|_)([a-z])/g, (_, __, letter: string) =>
    letter.toUpperCase(),
  );

let out =
  "// Generated by `pnpm --filter @cz-epf/api db:types` from the migrated\n" +
  "// database. Do not edit: change a migration and regenerate.\n";
for (const [table, lines] of tables) {
  out += `\n/** A row of \`${table}\`. */\nexport interface ${pascal(table)}Row {\n${lines.join("\n")}\n}\n`;
}
writeFileSync(new URL("../src/db.generated.ts", import.meta.url), out);
console.log(`wrote src/db.generated.ts: ${tables.size} tables`);
